version: "3"
services:
  app:
    build: ./app
    links:
      - db
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: "on"
      FLASK_APP: ./rest.py
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro